# Generated by Django 5.2.4 on 2025-07-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_vote',
            new_name='vote_to_skip',
        ),
    ]
